# ワークフロー名
name: test-schedule
on:
  schedule:
    # 定期実行する時間
    - cron: '43 13 * * *'

jobs:
  sample-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script
        run: |
          python main.py
